### ISSUE TITLE
Food Dye Ingredient Should Accept listAllwater

### ISSUE THREAD

**Issue by CSX8600** [Mesabrook-Development-Team/Immersibrook#78]
Food Dye only accepts a water bucket. This is very difficult to achieve in automated manufacturing. Please change all food dyes to utilize `listAllwater` instead of a water bucket.
![image](https://github.com/Mesabrook-Development-Team/Immersibrook/assets/23085858/20dcf9b9-4702-462e-bbfb-e73d05132e83)

**Comment by RavenholmZombie** [comment]
Fix in progress

**Comment by RavenholmZombie** [comment]
Fixed in https://github.com/Mesabrook-Development-Team/Immersibrook/commit/0acc1b6dfaef8e6ad1015cb6d3883e801863c7ed
